version: "3"
services:
  db:
    image: postgres
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pandamansecretpassword
      - POSTGRES_DB=oekaki
      - DATABASE_HOST=localhost
  backend:
    image: pandaman64/oekaki-backend:latest
    container_name: oekaki-backend
    environment:
      - DATABASE_URL=postgres://postgres:pandamansecretpassword@db/oekaki
    ports:
      - "8000:8000"
    depends_on:
      - db
  client:
    image: pandaman64/oekaki-client:latest
    container_name: oekaki-client
    environment:
      - BACKEND_URL=http://backend:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
